Remove the backslash in a weird split line url.
error: multi-line comment [-Werror=comment]

Originally, this was an escaped space, which also made no sense.
The original website doesn't exist.  Maybe this is the new page.

http://www.linz.govt.nz/data/geodetic-system/coordinate-conversion/projection-conversions/new-zealand-map-grid

Is is not https://epsg.io/27200 ?

NZGD49 / New Zealand Map Grid -- New Zealand Map Grid (NZMG)


git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@37883 f0d54148-0727-0410-94bb-9a71ac55c965