Remove unused bUpdateAccess from OGRODBCTableLayer.
./ogr_odbc.h:92:25: error: private field 'bUpdateAccess' is not used
      [-Werror,-Wunused-private-field]

git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@35193 f0d54148-0727-0410-94bb-9a71ac55c965