Possible fixes for build failures with r35545
trunk_mingw failed with:

gdaldem_lib.cpp: In function ‘float ComputeVal(int, T, int, T*, float, typename GDALGeneric3x3ProcessingAlg<T>::type, void*, int) [with T = float]’:
gdaldem_lib.cpp:183: error: ‘isnan’ was not declared in this scope

Added cpl_port.h first.  This might fix the problem or I need to
revert the changes to the includes.

MS VC12 failed with:

c:\projects\gdal-coverage\gdal\apps\gdaldem_lib.cpp(639) : warning C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        c:\projects\gdal-coverage\gdal\apps\gdaldem_lib.cpp(361) : definition of 'i' ignored
        c:\projects\gdal-coverage\gdal\apps\gdaldem_lib.cpp(446) : definition of 'i' use

Added a scope around the first for loop to make it very obvious that
the i vars are not related.


git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@35546 f0d54148-0727-0410-94bb-9a71ac55c965