Try to silence visual studio complaints in s57reader.cpp.
- error C2440: 'static_cast' : cannot convert from 'OGRGeometryCollection *' to 'OGRGeometryH'
- warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)


git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@32438 f0d54148-0727-0410-94bb-9a71ac55c965